name: 'Jobs Updater'
description: "The jobs updater will respond on some trigger, and them parse a jobs file for changes, posting a field of interest to slack."
inputs:
  filename:
    description: the filename for the jobs
    required: true    
  key:
    description: The key of the list to post (defaults to url)
    required: false
    default: url
  test:
    description: Test the updater (ensure there are jobs)
    required: true
    default: false
  deploy:
    description: Deploy to slack?
    required: true
    default: true
# If you want to post to Twitter, all of these credentials are required for a specific user

  # API keys are typically generated on behalf of a user (at the bottom of the interface)
  twitter_deploy:
    description: Boolean to deploy to Twitter
    required: false
  twitter_api_key:
    description: API key generated for the user account to tweet
    required: false
  twitter_api_secret:
    description: API secret generated for the user account to tweet
    required: false

  # Consumer keys are at the top of the developer interface, overall for the app (not a particular user)
  twitter_consumer_key:
    description: consumer key generated for the entire app
    required: false
  twitter_consumer_secret:
    description: consumer secret generated for the entire app
    required: false

outputs:
  fields:
    description: New fields parsed
    value: ${{ steps.jobs-updater.outputs.fields }}    
  matrix:
    description: Matrix (list of lists) with value (index 1), icon (index 2) and full message (index 3)
    value: ${{ steps.jobs-updater.outputs.matrix }}
  empty_matrix: 
    description: true if empty, false otherwise
    value: ${{ steps.jobs-updated.outputs.empty_matrix }}
    
runs:
  using: "composite"
  steps:
    - name: Install Python Dependencies
      run: |
          pip install pyyaml requests
          pip install git+https://github.com/tweepy/tweepy.git
      shell: bash

    - name: Run action entrypoint
      id: jobs-updater
      env:
        INPUT_FILENAME: ${{ inputs.filename }}
        INPUT_KEY: ${{ inputs.key }}
        CURRENT_SHA: ${{ github.sha }}
        ACTION_DIR: ${{ github.action_path }}
        INPUT_REPO: ${{ github.repository }}
        INPUT_TEST: ${{ inputs.test }}
        INPUT_DEPLOY: ${{ inputs.deploy }}
        TWITTER_DEPLOY: ${{ inputs.twitter_deploy }}
        TWITTER_API_KEY: ${{ inputs.twitter_api_key }}
        TWITTER_API_SECRET: ${{ inputs.twitter_api_secret }}
        TWITTER_CONSUMER_KEY: ${{ inputs.twitter_consumer_key }}
        TWITTER_CONSUMER_SECRET: ${{ inputs.twitter_consumer_secret }}
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
