name: 'Jobs Updater'
description: "The jobs updater will respond on some trigger, and them parse a jobs file for changes, posting a field of interest to slack."
inputs:
  filename:
    description: the filename for the jobs
    required: true    
  key:
    description: The key of the list to post (defaults to url)
    required: false
    default: url
  test:
    description: Test the updater (ensure there are jobs)
    required: true
    default: false
  deploy:
    description: Deploy to slack?
    required: true
    default: true

outputs:
  fields:
    description: New fields parsed
    value: ${{ steps.jobs-updater.outputs.fields }}    
  matrix:
    description: Matrix (list of lists) with value (index 1), icon (index 2) and full message (index 3)
    value: ${{ steps.jobs-updater.outputs.matrix }}    
    
runs:
  using: "composite"
  steps:
    - name: Install Python Dependencies
      run: pip install pyyaml requests
      shell: bash

    - name: Run action entrypoint
      id: jobs-updater
      env:
        INPUT_FILENAME: ${{ inputs.filename }}
        INPUT_KEY: ${{ inputs.key }}
        CURRENT_SHA: ${{ github.sha }}
        ACTION_DIR: ${{ github.action_path }}
        INPUT_REPO: ${{ github.repository }}
        INPUT_TEST: ${{ inputs.test }}
        INPUT_DEPLOY: ${{ inputs.deploy }}
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
