name: 'Jobs Updater'
description: "The jobs updater will respond on some trigger, and them parse a jobs file for changes, posting a field of interest to slack."
inputs:
  main: 
    description: main branch to compare to (defaults to main)
    required: false
    default: main
  filename:
    description: the filename for the jobs
    required: true    
  key:
    description: The key of the list to post (defaults to url)
    required: false
    default: url

outputs:
  fields:
    description: New fields parsed
    
runs:
  using: "composite"
  steps:
    - name: Install Python Dependencies
      run: pip install pyyaml requests
      shell: bash

    - name: Run action entrypoint
      id: jobs-updater
      env:
        INPUT_FILENAME: ${{ inputs.filename }}
        INPUT_MAIN: ${{ inputs.main }}
        INPUT_KEY: ${{ inputs.key }}
        ACTION_DIR: ${{ github.action_path }}
        INPUT_REPO: ${{ github.repository }}
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
